name: "build"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Run the notebooks
        run: |
          cd notebooks
          pip install -r requirements.txt
          for f in *.ipynb; 
            do echo "Processing $f file...";
            # jupyter nbconvert --execute --to notebook --inplace $f
            jupyter nbconvert $f --to slides
          done
          mkdir _site
          mv *.html _site
          ls -las
      - name: Build local Jupyter
        run: |
          cd notebooks
          docker build -t jupyter .
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: notebooks/_site # The folder the action should deploy.